### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by lexcorp** [linuxserver/gclient#2]
How tu run this?

**Comment by pagdot** [comment]
```
git clone https://github.com/linuxserver/gclient
cd gclient
npm install
node app.js
```

You need to configure your server in [app.js#L13](https://github.com/linuxserver/gclient/blob/master/app.js#L13) and [app.js#L44](https://github.com/linuxserver/gclient/blob/master/app.js#L44) first (and have guacd running already) .

**Comment by thelamer** [comment]
As @pagdot pointed out credentials are hard coded and the token it passes by default is for a local RDP connection. I do not have any current plans to turn this into a standalone application with a form for setting credentials as this does what we at Linuxserver need it to do. 
This is kind of an internal project used to support downstream apps like our Rdesktop-web baseimage and the stuff that runs on it. https://github.com/linuxserver/docker-baseimage-rdesktop-web
We do things like hard code the login credentials to abc:abc, it is not really meant to be a consumer facing nodejs application, but you are free to use any of the code examples in this repo to spin up an app that works for you.
