### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by lexcorp** [linuxserver/gclient#3]
guac.min.js:1 WebSocket connection to 'wss://infra.villahermosa.local:8443/guacamole/websocket-tunnel?token=%3C%-%20token%20-%%3E&width=1600&height=407?undefined' failed: Error during WebSocket handshake: Unexpected response code: 500
connect @ guac.min.js:1
connect @ guac.min.js:1
(anonymous) @ rdp.js:92

**Comment by thelamer** [comment]
This is kind of an internal project used to support downstream apps like our Rdesktop-web baseimage and the stuff that runs on it. 
We do things like hard code the login credentials to abc:abc, it is not really meant to be a consumer facing nodejs application, but you are free to use any of the code examples in this repo to spin up an app that works for you.
