### ISSUE TITLE
How can I send any file into local server to remote server ? 

### ISSUE THREAD

**Issue by mfarkan** [linuxserver/gclient#6]
Hello, I use guacomole-common.js 1.3.0 version and I did not achieve to send files for just drag and drop into files? Is it possible to do that with working just common-js ? I do not understand the guacd's documentation. Does guacd listen a specific folder and when I drag into that file it just accept and download the file into that folder ?

**Comment by fming** [comment]
how to achieve this? use the 3rd sftp library or mechanism of guacamole itself?

**Comment by thelamer** [comment]
I decided to not use guacamole's file tunneling and build a framework from the ground up to display folders, upload progress, etc etc. Instead this application expects to be running inside a container (specifically our rdesktop-web base image) and uses nodejs with off the shelf cloud commander ( https://cloudcmd.io/ ) and Pam authentication at the sys level. It is even tied specifically to our abc user.
Please try to understand the purpose of this project, it is not meant as a universal guacamole frontend it is specifically tailored to our needs.
