### ISSUE TITLE
Remove remote mouse pointer when leaving canvas

### ISSUE THREAD

**Issue by umardraz** [linuxserver/gclient#7]
Currently the pointer stays in the browser canvas whenever you leave it so It is much more seamless when there is only one mouse pointer.

please see the (attached screenshot).

and help me how we can fix this

![Double pointer](https://user-images.githubusercontent.com/3677378/118498562-9a087400-b73f-11eb-8fb8-48591baa9e61.png)

**Comment by thelamer** [comment]
This is expected behavior, when you are interacting with the canvas your mouse events are sent to the rendered endpoint and your system cursor is hidden. When you leave the screen it is not like the rendered endpoints mouse cursor ceases to exist.
